name: Flask CI
environment:
  MONGODB_DATA_DIR: "C:\Program Files\MongoDB\data"  
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Specify Windows environment

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you need

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install MongoDB
      - name: Install MongoDB
        run: |
          choco install mongodb -y

      # Start MongoDB (using environment variable for data path)
      - name: Start MongoDB
        run: |
          if ! which mongod.exe > /dev/null 2>&1; then
            echo "Error: mongod.exe not found. Please check the installation path."
            exit 1
          fi
          mongod.exe --dbpath "$MONGODB_DATA_DIR" --bind_ip 127.0.0.1

      # Set up Flask app
      - name: Set up Flask app
        run: |
          python app.py  # Starts the Flask app

      # Run tests
      - name: Run tests
        run: |
          pytest test/test_app.py
