name: Flask CI

on:
  pull_request:
    branches:
      - main_dev

jobs:
  build:
    runs-on: windows-latest  # Specify Windows environment

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you need

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install MongoDB
      - name: Install MongoDB
        run: |
          choco install mongodb -y

      # Start MongoDB (using environment variable for data path)
      # - name: Start MongoDB
      #   run: |
      #     if (Test-Path "C:\Program Files\MongoDB\Server\7.0\bin\mongod.exe") {
      #       "C:\Program Files\MongoDB\Server\7.0\bin\mongod.exe" --dbpath="C:\Program Files\MongoDB\data" --bind_ip 127.0.0.1
      #     } else {
      #       Write-Host "mongod.exe not found"
      #       exit 1
      #     }
      # Set up Flask app
      - name: Set up Flask app
        run: |
          Start-Process -NoNewWindow -FilePath "python" -ArgumentList "app.py"
          Start-Sleep -Seconds 10  # Wait for Flask to start

      # Run tests
      - name: Run tests
        run: |
          pytest test/test_app.py
